theme: jekyll-theme-minimal
title: STAPYT Formelsamling
description: Denne formelsamling er lavet til at give overblik over vigtige statistiske modeller og formler til kurset Statistisk Dataanalyse med Python 2025 ved Aarhus Universitet.
